### ISSUE TITLE
Local workspace file ('angular.json') could not be found.

### ISSUE THREAD

**Issue by ahoehma** [vaadin/base-starter-angular#8]
hoehmann@XXXXX MINGW64 /d/Dev/git/base-starter-angular (master)
$ ng serve
Local workspace file ('angular.json') could not be found.
Error: Local workspace file ('angular.json') could not be found.
    at WorkspaceLoader._getProjectWorkspaceFilePath (C:\Users\hoehmann\AppData\Roaming\npm\node_modules\@angular\cli\models\workspace-loader.js:37:19)
    at WorkspaceLoader.loadWorkspace (C:\Users\hoehmann\AppData\Roaming\npm\node_modules\@angular\cli\models\workspace-loader.js:24:21)
    at ServeCommand._loadWorkspaceAndArchitect (C:\Users\hoehmann\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:195:32)
    at ServeCommand.<anonymous> (C:\Users\hoehmann\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:47:25)
    at Generator.next (<anonymous>)
    at C:\Users\hoehmann\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\hoehmann\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:3:12)
    at ServeCommand.initialize (C:\Users\hoehmann\AppData\Roaming\npm\node_modules\@angular\cli\models\architect-command.js:46:16)
    at Object.<anonymous> (C:\Users\hoehmann\AppData\Roaming\npm\node_modules\@angular\cli\models\command-runner.js:87:23)

**Comment by limonte** [comment]
Thanks for reporting @ahoehma! This is because of recently released `@angular/cli`, here's the fix: #9

**Comment by molcik** [comment]
For people googling fix for this error: **[here is the answer (my blog)](https://filipmolcik.com/error-local-workspace-file-angular-json-could-not-be-found/)**

**Comment by jainrish** [comment]
This one solved it for me:
http://jiodev.com/questions/Local-workspace-file-angular-json-could-not-be-found

**Comment by BruceJay** [comment]
i solved the problem by following the following steps

1. npm uninstall  -g @angular/cli
2.npm cache verify
3. npm install -g  @angular/cli --no-optional 
4.ng new  new-project
5. ng s/ ng s -o

**Comment by Alexandar0** [comment]
If you run the command 'ng new my-app' when you are already in the app folder it opens yet another folder with the same name inside. Check whether you run the command 'ng serve' in the first or second folder. 
   Example:
   
   If you run 'ng serve' in:     C:\Users\hoehmann\my-app

   you need to run it in:        C:\Users\hoehmann\my-app\my-app
